<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Group 2, option 1</name>
   <tag></tag>
   <elementGuidId>d1e1cf66-b781-4ac6-9866-a3c1e0eca9b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-2-option-1-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-2-option-1-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fa04c079-003f-4d9e-aea8-07ac5c5278df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1n7v3ny-option</value>
      <webElementGuid>5e808087-6941-4474-ad4e-9c677b62ed4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-2-option-1-0</value>
      <webElementGuid>63e4b8dc-6468-4fa8-b149-af5e12428fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>48ac2b23-c84a-46b0-81bd-64c8ea93e676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Group 2, option 1</value>
      <webElementGuid>ca203d60-71ef-4081-9ad5-dc9ee3faa9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-2-option-1-0&quot;)</value>
      <webElementGuid>33faa0f0-5910-4394-88e8-b0cdf1c77934</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-option-1-0']</value>
      <webElementGuid>4c8cac8a-66ea-4f6e-8207-f83df645063b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='withOptGroup']/div[2]/div/div[2]/div[2]/div</value>
      <webElementGuid>29096152-f7eb-4058-977d-b6a5dd4eba8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group 2'])[1]/following::div[2]</value>
      <webElementGuid>9009614f-b15a-4f48-ab89-b8fa99ce86b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group 1, option 2'])[1]/following::div[4]</value>
      <webElementGuid>3fbc19cb-60e0-4ac5-8f8d-0dc8fc44b447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group 2, option 2'])[1]/preceding::div[1]</value>
      <webElementGuid>1798b9ff-1359-4969-8be3-13d40439fca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A root option'])[1]/preceding::div[2]</value>
      <webElementGuid>a27fff63-9b54-42c2-a8fa-97c2d2e3e74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Group 2, option 1']/parent::*</value>
      <webElementGuid>b1fef38d-c5de-4cf0-b581-395d7f5ee2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div/div[2]/div[2]/div</value>
      <webElementGuid>d0deb178-0c94-4bae-a54e-94419ecd6c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-2-option-1-0' and (text() = 'Group 2, option 1' or . = 'Group 2, option 1')]</value>
      <webElementGuid>cc5db597-8b73-4d99-ac28-9f7ce06aee75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
