<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_RedBlueGreenYellowPurpleBlackWhiteVo_537a50</name>
   <tag></tag>
   <elementGuidId>38351804-d066-4939-a963-26e3419f888f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='oldSelectMenu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#oldSelectMenu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ae45fe3c-961c-4d25-ac2a-7d6e42cb8a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oldSelectMenu</value>
      <webElementGuid>2c2c28d7-b577-4afd-9f76-64df2e2ec9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RedBlueGreenYellowPurpleBlackWhiteVoiletIndigoMagentaAqua</value>
      <webElementGuid>7353a3d6-c37e-4249-b80b-83aacb29f9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oldSelectMenu&quot;)</value>
      <webElementGuid>8e9adc22-bbef-4a3c-b786-3b9315fb0f01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='oldSelectMenu']</value>
      <webElementGuid>376a4a82-f5e9-4983-8c6c-71a981288351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selectMenuContainer']/div[6]/div/div/select</value>
      <webElementGuid>676bb67c-9481-4d61-a948-f0b73048876a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Old Style Select Menu'])[1]/following::select[1]</value>
      <webElementGuid>d3813ae3-1487-4db4-814f-a771084b72a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Title'])[1]/following::select[1]</value>
      <webElementGuid>42573fdd-0403-4a1d-88e6-3be97792b075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multiselect drop down'])[1]/preceding::select[1]</value>
      <webElementGuid>cb1a55e7-da7f-47ec-b18d-be4d9b51ef2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select...'])[1]/preceding::select[1]</value>
      <webElementGuid>f2c4a696-b500-4a80-ad0a-6c559f310fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>de1bf21a-bc15-4060-a853-c1373df2600b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'oldSelectMenu' and (text() = 'RedBlueGreenYellowPurpleBlackWhiteVoiletIndigoMagentaAqua' or . = 'RedBlueGreenYellowPurpleBlackWhiteVoiletIndigoMagentaAqua')]</value>
      <webElementGuid>af1e737d-a4cd-4035-b217-130dce2cca0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
